#!/bin/bash

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🗄️  Database Migrations - Ready to Apply"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Two new migrations created:"
echo "  1. Custom Pricing (client-level pricing)"
echo "  2. Billing Source Control (prevent double billing)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📄 MIGRATION 1: Custom Pricing"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
cat supabase/migrations/20251006_add_custom_pricing_to_memberships.sql
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📄 MIGRATION 2: Billing Source Control"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
cat supabase/migrations/20251006_add_billing_source_control.sql
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ How to Apply These Migrations"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🌐 Supabase SQL Editor:"
echo "   https://supabase.com/dashboard/project/lzlrojoaxrqvmhempnkn/sql"
echo ""
echo "1. Click 'New Query'"
echo "2. Copy SQL from MIGRATION 1 above"
echo "3. Click 'Run'"
echo "4. Repeat for MIGRATION 2"
echo ""
