name: CI

on:
  pull_request:
    paths:
      - 'app/**'
      - 'components/**'
      - 'lib/**'
      - 'scripts/**'
      - 'packages/**'
      - 'gym-coach-platform/**'
      - 'atlas-fitness-mobile/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'jest.config.js'
      - 'gym-coach-platform/jest.config.js'
      - 'tsconfig.json'
      - 'tsconfig.strict.json'
  push:
    branches: [main]
    paths:
      - 'app/**'
      - 'components/**'
      - 'lib/**'
      - 'scripts/**'
      - 'packages/**'
      - 'gym-coach-platform/**'
      - 'atlas-fitness-mobile/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'jest.config.js'
      - 'gym-coach-platform/jest.config.js'
      - 'tsconfig.json'
      - 'tsconfig.strict.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run unit tests (pass with no tests)
        run: npm test --silent

      - name: Upload jest results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jest-logs
          path: |
            junit.xml
            coverage/
          if-no-files-found: ignore