name: CI
on:
  pull_request:
    paths:
      - 'app/**'
      - 'src/**'
      - 'tests/**'
      - '__tests__/**'
      - 'gym-coach-platform/**'
      - 'jest.config.js'
      - 'package.json'
      - 'package-lock.json'
      - 'pnpm-lock.yaml'
      - 'scripts/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test --silent -- --passWithNoTests