name: Claude Design Review

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'app/**'
      - 'components/**'
      - 'lib/**'
      - 'supabase/**'
      - 'pages/**'
      - 'package.json'
      - 'next.config.*'
      - 'tsconfig.*'

jobs:
  design-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          
      - name: Install Playwright
        run: npx playwright install chromium
        
      - name: Run accessibility tests
        run: |
          npx playwright test tests/ui/accessibility/ --reporter=json > a11y-results.json || true
        
      - name: Take screenshots of key routes
        run: |
          npx playwright test tests/ui/screenshots/ --reporter=json > screenshot-results.json || true
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: design-review-artifacts
          path: |
            a11y-results.json
            screenshot-results.json
            test-results/
            
      - name: Claude Design Review
        if: github.event_name == 'pull_request'
        uses: anthropics/claude-code-action@v1
        with:
          api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          review-type: 'design'
          config-file: 'CLAUDE.md'
          artifacts-path: './test-results'
          comment-on-pr: true
          suggest-fixes: true
          max-diff-size: 500
          
      - name: Generate design report
        run: |
          echo "## Design Review Summary" > design-report.md
          echo "- Accessibility violations found: $(jq '.violations | length' a11y-results.json 2>/dev/null || echo 0)" >> design-report.md
          echo "- Screenshots captured: $(ls test-results/*.png 2>/dev/null | wc -l || echo 0)" >> design-report.md
          cat design-report.md
          
      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('design-report.md', 'utf8');
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            });