name: Claude Design Review

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'app/**'
      - 'components/**'
      - 'lib/**'
      - 'pages/**'
      - 'supabase/**'
      - 'styles/**'
      - 'package.json'
      - 'next.config.*'
      - 'tsconfig.*'
      - '!docs/**'
      - '!.github/**'
      - '!.cursor/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  design-review:
    # Skip for chore/ci/docs PRs (optional but handy)
    if: >
      ${{
        !startsWith(github.head_ref, 'chore/') &&
        !contains(github.event.pull_request.title, 'chore') &&
        !contains(github.event.pull_request.title, 'docs')
      }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      # … keep your existing steps here …
