name: Nightly QA (GitHub-only)

on:
  schedule:
    - cron: "0 2 * * *"   # 02:00 UTC nightly
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Make a tiny, harmless change so a commit always exists
      - name: Prepare host commit
        run: |
          mkdir -p .github/automation
          echo "nightly: $(date -u)" > .github/automation/nightly-heartbeat.txt

      # Open or update the sticky host PR on a fixed branch
      - name: Open/Update Nightly Host PR
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          branch: automation/nightly-qa
          title: 'chore(nightly): full QA host PR'
          commit-message: 'chore(nightly): trigger nightly QA'
          body: |
            **Nightly QA host PR**

            > Cursor, please run full QA for `${{ github.repository }}` on branch `${{ github.ref_name || 'main' }}`:
            - Typecheck
            - Lint
            - Unit/Integration tests with coverage
            - Playwright E2E (if present)
            - Raise coverage on changed modules
            - Open minimal PRs/commits with fixes and a short summary
            - **Do not** modify RLS or payments; **no** prod DB migrations

            Nightly run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          labels: automation, nightly
          draft: false

      # Optional: add a label you use for routing in GitHub
      - name: Add labels (optional)
        if: steps.cpr.outputs.pull-request-number
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number('${{ steps.cpr.outputs.pull-request-number }}'),
              labels: ['cursor:nightly']
            });
