name: Cursor: On PR (GitHub-only)

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  prompt-cursor:
    runs-on: ubuntu-latest
    steps:
      - name: Detect user token availability
        run: |
          if [ -n "${{ secrets.GH_USER_TOKEN }}" ]; then
            echo "HAS_GH_USER_TOKEN=true" >> "$GITHUB_ENV"
          else
            echo "HAS_GH_USER_TOKEN=false" >> "$GITHUB_ENV"
          fi

      # Post as YOU (if GH_USER_TOKEN is set)
      - name: Upsert PR prompt comment (user)
        if: ${{ env.HAS_GH_USER_TOKEN == 'true' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GH_USER_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          comment-author: ${{ github.actor }}
          body: |
            <!-- cursor-pr-prompt -->
            @cursoragent please review this PR for **${{ github.repository }}**  
            PR **#${{ github.event.pull_request.number }}** on branch **${{ github.event.pull_request.head.ref }}**:

            • Run typecheck and lint  
            • Run unit/integration tests with coverage  
            • If anything fails, push a minimal fix **and add a regression test** to this PR  
            • **Do not** modify RLS or payments; **no** prod DB migrations

            Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      # Fallback: post as GitHub Actions bot
      - name: Upsert PR prompt comment (bot)
        if: ${{ env.HAS_GH_USER_TOKEN != 'true' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            <!-- cursor-pr-prompt -->
            @cursoragent please review this PR for **${{ github.repository }}**  
            PR **#${{ github.event.pull_request.number }}** on branch **${{ github.event.pull_request.head.ref }}**:

            • Run typecheck and lint  
            • Run unit/integration tests with coverage  
            • If anything fails, push a minimal fix **and add a regression test** to this PR  
            • **Do not** modify RLS or payments; **no** prod DB migrations

            Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
