name: Cursor: On CI failure (GitHub-only)

on:
  workflow_run:
    workflows: ["CI", "E2E Flow Tests", "Next.js App Router Lint"]
    types: [completed]

permissions:
  pull-requests: write
  contents: read

jobs:
  prompt-on-failure:
    runs-on: ubuntu-latest
    if: >
      ${{
        github.event.workflow_run.conclusion != 'success' &&
        github.event.workflow_run.event == 'pull_request' &&
        github.event.workflow_run.pull_requests[0].number != null
      }}
    steps:
      - name: Extract PR / branch / URLs
        id: info
        run: |
          PR_NUMBER="${{ github.event.workflow_run.pull_requests[0].number }}"
          BRANCH="${{ github.event.workflow_run.head_branch }}"
          REPO="${{ github.repository }}"
          RUN_URL="${{ github.event.workflow_run.html_url }}"
          echo "pr=$PR_NUMBER"   >> $GITHUB_OUTPUT
          echo "branch=$BRANCH"  >> $GITHUB_OUTPUT
          echo "repo=$REPO"      >> $GITHUB_OUTPUT
          echo "run_url=$RUN_URL" >> $GITHUB_OUTPUT

      - name: Detect user token availability
        run: |
          if [ -n "${{ secrets.GH_USER_TOKEN }}" ]; then
            echo "HAS_GH_USER_TOKEN=true" >> "$GITHUB_ENV"
          else
            echo "HAS_GH_USER_TOKEN=false" >> "$GITHUB_ENV"
          fi

      # Post as YOU (if GH_USER_TOKEN is set)
      - name: Upsert CI fail prompt (user)
        if: ${{ env.HAS_GH_USER_TOKEN == 'true' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GH_USER_TOKEN }}
          issue-number: ${{ steps.info.outputs.pr }}
          body-includes: "<!-- cursor-ci-fail -->"
          edit-mode: replace
          comment-author: ${{ github.actor }}
          body: |
            <!-- cursor-ci-fail -->
            @cursoragent **CI failed** for **${{ steps.info.outputs.repo }}**, branch **${{ steps.info.outputs.branch }}** (PR #${{ steps.info.outputs.pr }}).

            Failing run: ${{ steps.info.outputs.run_url }}

            Please:
            • Fetch the failing logs  
            • Push a **minimal** fix and add a **regression test** to this PR  
            • **Do not** change RLS or payments; **no** prod DB migrations

      # Fallback: post as GitHub Actions bot
      - name: Upsert CI fail prompt (bot)
        if: ${{ env.HAS_GH_USER_TOKEN != 'true' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ steps.info.outputs.pr }}
          body-includes: "<!-- cursor-ci-fail -->"
          edit-mode: replace
          body: |
            <!-- cursor-ci-fail -->
            @cursoragent **CI failed** for **${{ steps.info.outputs.repo }}**, branch **${{ steps.info.outputs.branch }}** (PR #${{ steps.info.outputs.pr }}).

            Failing run: ${{ steps.info.outputs.run_url }}

            Please:
            • Fetch the failing logs  
            • Push a **minimal** fix and add a **regression test** to this PR  
            • **Do not** change RLS or payments; **no** prod DB migrations
