      - name: Send to Slack
        env:
          SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID_TESTS }} # or _BUGFIX in the CI-fail workflow
          CURSOR_USER_ID: ${{ secrets.CURSOR_USER_ID }}           # UXXXXXXXX you saved earlier
          TEXT: "<@${{ secrets.CURSOR_USER_ID }}> [repo=${{ steps.build.outputs.REPO || github.repository }}, branch=${{ steps.build.outputs.BRANCH || github.ref_name }}] run unit and integration tests; if anything fails, push a small fix and add a regression test. Keep the diff minimal; do not change RLS or payments."
        run: |
          curl -s -X POST https://slack.com/api/chat.postMessage \
            -H "Authorization: Bearer $SLACK_USER_TOKEN" \
            -H "Content-type: application/json" \
            --data "{\"channel\":\"$SLACK_CHANNEL_ID\",\"text\":\"$TEXT\",\"link_names\":true,\"unfurl_links\":false}"
