      - name: Send to Slack
        env:
          SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}   # must start xoxp-
          CURSOR_USER_ID:  ${{ secrets.CURSOR_USER_ID }}       # Uxxxx for @Cursor
          CHANNEL:         ${{ steps.build.outputs.CHANNEL }}
          REPO:            ${{ steps.build.outputs.REPO }}
          BRANCH:          ${{ steps.build.outputs.BRANCH }}
        run: |
          set -euo pipefail

          TEXT="<@${CURSOR_USER_ID}> [repo=${REPO}, branch=${BRANCH}] run full nightly QA: typecheck, lint, unit/integration tests with coverage, Playwright E2E if available; raise coverage on changed modules; open a minimal PR with fixes and a short summary. Keep the diff minimal; do not change RLS or payments; no prod migrations."

          # JSON-escape the text using Python (installed on ubuntu-latest)
          ESCAPED_TEXT=$(python3 - <<'PY'
          import json,sys,os
          print(json.dumps(os.environ["TEXT"]))
          PY
          )

          PAYLOAD=$(cat <<JSON
          {
            "channel": "${CHANNEL}",
            "text": ${ESCAPED_TEXT},
            "link_names": true,
            "unfurl_links": false
          }
          JSON
          )

          curl -sS -X POST https://slack.com/api/chat.postMessage \
            -H "Authorization: Bearer $SLACK_USER_TOKEN" \
            -H "Content-type: application/json; charset=utf-8" \
            --data "$PAYLOAD"
