      - name: Send to Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID_TESTS }}
          CURSOR_USER_ID: ${{ secrets.CURSOR_USER_ID }}
          REPO: ${{ steps.build.outputs.REPO }}
          BRANCH: ${{ steps.build.outputs.BRANCH }}
        run: |
          TEXT="<@${CURSOR_USER_ID}> [repo=${REPO}, branch=${BRANCH}] run unit and integration tests; if anything fails, push a small fix and add a regression test to this PR. Keep the diff minimal; do not change RLS or payments."
          curl -s -X POST https://slack.com/api/chat.postMessage \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H 'Content-type: application/json' \
            --data "{\"channel\":\"$SLACK_CHANNEL_ID\",\"text\":\"$TEXT\",\"link_names\":true,\"unfurl_links\":false}"
