name: Rolling PR maintainer

on:
  push:
    branches:
      - cursor/rolling-fixes
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  ensure-rolling-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure jq is installed
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Verify GitHub CLI available
        run: gh --version

      - name: Create or update rolling PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          owner="${REPO%%/*}"
          repo="${REPO##*/}"
          head="cursor/rolling-fixes"
          base="main"
          title="chore: rolling Cursor fixes"
          ciLink="https://github.com/${owner}/${repo}/actions?query=branch%3A${head}"
          body=$(cat <<'BODY'
          Rolling PR to accumulate small Cursor-driven fixes.

          - Vercel preview: TBD
          - Latest CI run: CI_LINK

          Running checklist:
          - [x] Initialize rolling PR

          Manual review notes:
          - N/A
          BODY
          )
          body=${body/CI_LINK/${ciLink}}

          # If PR exists, update; else create
          if gh pr view "${head}" >/dev/null 2>&1; then
            gh pr edit "${head}" --title "$title" --body "$body"
          else
            gh pr create --title "$title" --body "$body" --base "$base" --head "$head"
          fi
