name: Rolling PR maintainer

on:
  push:
    branches:
      - cursor/rolling-fixes
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  ensure-rolling-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create or update rolling PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          owner="${REPO%%/*}"
          repo="${REPO##*/}"
          head="cursor/rolling-fixes"
          base="main"
          title="chore: rolling Cursor fixes"
          ciLink="https://github.com/${owner}/${repo}/actions?query=branch%3A${head}"
          vercelPreview="TBD"
          body=$(cat <<'BODY'
          Rolling PR to accumulate small Cursor-driven fixes.

          - Vercel preview: TBD
          - Latest CI run: CI_LINK

          Running checklist:
          - [x] Initialize rolling PR

          Manual review notes:
          - N/A
          BODY
          )
          body=${body/CI_LINK/${ciLink}}

          # Find existing PR
          existing=$(curl -s -H "Authorization: token ${GH_TOKEN}" -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${owner}/${repo}/pulls?state=open&head=${owner}:${head}&base=${base}")
          number=$(echo "$existing" | sed -nE 's/.*"number":\s*([0-9]+).*/\1/p' | head -n1 || true)

          if [ -n "${number:-}" ]; then
            curl -s -X PATCH -H "Authorization: token ${GH_TOKEN}" -H "Accept: application/vnd.github+json" \
              -d "$(jq -n --arg title "$title" --arg body "$body" '{title:$title, body:$body}')" \
              "https://api.github.com/repos/${owner}/${repo}/pulls/${number}" > /dev/null || true
          else
            curl -s -X POST -H "Authorization: token ${GH_TOKEN}" -H "Accept: application/vnd.github+json" \
              -d "$(jq -n --arg title "$title" --arg head "$head" --arg base "$base" --arg body "$body" '{title:$title, head:$head, base:$base, body:$body, draft:false}')" \
              "https://api.github.com/repos/${owner}/${repo}/pulls" > /dev/null || true
          fi
